config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :reviews
  get 'pages/home'
  get 'pages/directions'
  get 'pages/about'
  root 'pages#home'
  get 'auth/dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def directions
  end
  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :customerReview)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedBaron</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar fixed-top navbar-dark bg-dark">
      <%= link_to "The Red Baron", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "About", pages_about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Menus", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Directions", pages_directions_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Schedule A Pick-Up", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", "#", class: "nav-link" %>
          </li>
          <span class="navbar-text">
            <hr>
            <p> 220 Airport Access Rd, Southbridge, MA 01550 </p>
            <hr>
            <p> (508) 765-5800 </p>
            <hr>
            <p> Hours </p>
          </span>
        </ul>
      </div>
      </nav>
    </div>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <div class="container-fluid">
      <ul class="navbar fixed-bottom nav nav-justified bg-dark">
        <li class="nav-item color-dark">
          <a class="nav-link linkreset" href="#">220 Airport Access Rd, Southbridge, MA 01550</a>
        </li>
        <li class="nav-item">
          <a class="nav-link linkreset" href="#">(508) 765-5800</a>
        </li>
        <li class="nav-item">
          <a class="nav-link linkreset" href="#">Facebook Link</a>
        </li>
      </ul>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-4 text-center" style="margin-top: 5%">
    <%= @section_about%>
  </div>
  <div class="col-4 p-0">
    <div class="about-slider">
      <div style="background-image: url('https://dummyimage.com/2000x2000/000/fff.jpg')"></div>
      <div style="background-image: url('https://dummyimage.com/2000x2000/000/fff.jpg')"></div>
      <div style="background-image: url('https://dummyimage.com/2000x2000/000/fff.jpg')"></div>
    </div>
  </div>
  <div class="col-4 text-center" style="margin-top: 5%">
    Reviews
  </div>
</div>

app/views/pages/directions.html.erb
<div class="p56">
  <div class="row">
    <div class="col-xl-5">
      <div class="">
        <h1 class="text-center"> Red Baron Diner Inc </h1>
        <hr>
        <h3> 220 Airport Access Rd, Southbridge, MA 01550 </h3>
        <hr>
        <p> Located near the airport in Southbridge MA, this hidden gem will be sure to impress those who visit </p>
      </div>
    </div>
    <div class="col">
      <div class="text-center">
        <iframe width="800" height="800" frameborder="0" src="https://www.bing.com/maps/embed?h=800&w=800&cp=42.09994191210413~-72.03761100769044&lvl=10&typ=d&sty=r&src=SHELL&FORM=MBEDV8" scrolling="no">
        </iframe>
        <div style="white-space: nowrap; text-align: center; width: 800px; padding: 6px 0;">
          <a id="largeMapLink" target="_blank" href="https://www.bing.com/maps?cp=42.09994191210413~-72.03761100769044&amp;sty=r&amp;lvl=10&amp;FORM=MBEDLD">View Larger Map</a> &nbsp; | &nbsp;
          <a id="dirMapLink" target="_blank" href="https://www.bing.com/maps/directions?cp=42.09994191210413~-72.03761100769044&amp;sty=r&amp;lvl=10&amp;rtp=~pos.42.42039910934823_-71.46087689193126____&amp;FORM=MBEDLD">Get Directions</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid slickyboi p-0">
  <div class="single-item">
     <div id="helloWorld" style="background-image: url('<%= asset_path "diner" %>')"></div>
     <div style="background-image: url('<%= asset_path "diner2" %>')"></div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :customerReview %>
    <%= form.text_area :customerReview %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Customerreview</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.customerReview %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Customerreview:</strong>
  <%= @review.customerReview %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.description %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @section.description %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>